// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package user

import (
	"database/sql"
)

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Picture   sql.NullString `json:"picture"`
}
