// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package user

import ()

type User struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
}
